# Generated by Django 6.1 on 2026-09-04 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.CharField(max_length=20)),
                ('resident_name', models.CharField(max_length=150)),
                ('move_type', models.CharField(choices=[('move_in', 'Move in'), ('move_out', 'Move out')], max_length=10)),
                ('requested_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoveRequestChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('move_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='accounts.moverequest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
