# Generated by Django 6.1 on 2026-09-13 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancefee',
            name='breakdown_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='maintenancefee',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancefee',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancefee',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('card', 'Credit / Debit Card'), ('net_banking', 'Net Banking'), ('cash', 'Cash / Cheque')], default='card', max_length=30),
        ),
        migrations.AddField(
            model_name='maintenancefee',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='maintenancefee',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='maintenancefee',
            name='period',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='SocietyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=20)),
                ('category', models.CharField(choices=[('maintenance', 'Maintenance Collections'), ('facility', 'Facility Booking'), ('penalty', 'Late Fees / Penalties'), ('other_income', 'Other Income'), ('security', 'Security Staff & Guards'), ('housekeeping', 'Housekeeping & Sanitation'), ('utilities', 'Electricity & Water Bills'), ('repairs', 'Lift & Electrical Repairs'), ('gardening', 'Landscaping & Gardening'), ('admin', 'Administrative & Audit'), ('other_expense', 'Other Expense')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
