# Generated by Django 6.1 on 2026-09-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_staffpass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestapproval',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='guestapproval',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestapproval',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='guestapproval',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='package',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='company',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='package',
            name='delivery_person_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='delivery_person_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='tracking_pin',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='staffpass',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='visitor',
            name='entry_gate',
            field=models.CharField(default='Main Gate', max_length=50),
        ),
        migrations.AddField(
            model_name='visitor',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='otp',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='visitor',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='visitor',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
